name: catboost
class_path: src.models.classical.catboost_model.CatBoostModel
task: classification
params:
  iterations: 300
  depth: 4
  learning_rate: 0.03
  auto_class_weights: Balanced
  random_seed: 42
  verbose: false
