name: logistic_regression
class_path: src.models.classical.sklearn_models.LogisticRegressionModel
task: classification
params:
  C: 0.5
  penalty: l2
  solver: liblinear
  class_weight: balanced
  max_iter: 2000
  random_state: 42
