experiment_name: corn_monthly_cnn_all_numeric_spike_platt
seed: 42
output_dir: experiments
data_config: data_cnn_all_numeric_spike_platt
models:
  - name: fcn
    enabled: true
    config: model/fcn_classifier.yaml
  - name: resnet1d
    enabled: true
    config: model/resnet1d_classifier.yaml
  - name: inceptiontime
    enabled: true
    config: model/inceptiontime_classifier.yaml
  - name: tcn
    enabled: true
    config: model/tcn_classifier.yaml
  - name: rocket
    enabled: true
    config: model/rocket_classifier.yaml
  - name: minirocket
    enabled: true
    config: model/minirocket_classifier.yaml
  - name: multirocket
    enabled: true
    config: model/multirocket_classifier.yaml
