experiment_name: corn_monthly_top_ml_raw05
seed: 42
output_dir: experiments
data_config: data_top_raw05
models:
  - name: mlp
    enabled: true
    config: model/mlp_classifier.yaml
  - name: knn
    enabled: true
    config: model/knn_classifier.yaml
  - name: gaussian_nb
    enabled: true
    config: model/gaussian_nb_classifier.yaml
  - name: rbf_svc
    enabled: true
    config: model/rbf_svc_classifier.yaml
